name: safe_space_plugin
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  assets_audio_player: ^3.0.6
  assets_audio_player_web: ^3.0.6
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^2.0.1
  flutter_phone_direct_caller: ^2.1.1
  flutter_sms: ^2.3.3
  flutter_web_plugins:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  from_css_color: ^2.0.0
  geolocator: ^9.0.2
  go_router: ^6.0.1
  google_fonts: ^3.0.1
  intl: ^0.18.0
  json_path: ^0.4.2
  mapbox_search: ^3.0.1+2
  material: ^1.0.0+2
  page_transition: ^2.0.9
  plugin_platform_interface: ^2.0.2
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  sms: ^0.2.4
  sqflite: ^2.2.2
  table_calendar: ^3.0.9
  timeago: ^3.2.2
  url_launcher: ^6.1.7
  webviewx: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: net.mysafespace.safe_space_plugin
        pluginClass: SafeSpacePlugin
      ios:
        pluginClass: SafeSpacePlugin
      linux:
        pluginClass: SafeSpacePlugin
      macos:
        pluginClass: SafeSpacePlugin
      windows:
        pluginClass: SafeSpacePluginCApi
      web:
        pluginClass: SafeSpacePluginWeb
        fileName: safe_space_plugin_web.dart

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
  # To add assets to your plugin package, add an assets section, like this:
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
