// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkjKdojYxPym7BUT84dMAmAPFEZ1ZEBLo',
    appId: '1:1013247766191:web:fd16613bd5b2ec679bae5a',
    messagingSenderId: '1013247766191',
    projectId: 'mysafespaceapp-d5bc3',
    authDomain: 'mysafespaceapp-d5bc3.firebaseapp.com',
    databaseURL: 'https://mysafespaceapp-d5bc3-default-rtdb.firebaseio.com',
    storageBucket: 'mysafespaceapp-d5bc3.appspot.com',
    measurementId: 'G-QREECHZERK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaUIQ1JHaP1obO8qORiefVab9F0gFvc9Q',
    appId: '1:1013247766191:android:a1e20134a94d85759bae5a',
    messagingSenderId: '1013247766191',
    projectId: 'mysafespaceapp-d5bc3',
    databaseURL: 'https://mysafespaceapp-d5bc3-default-rtdb.firebaseio.com',
    storageBucket: 'mysafespaceapp-d5bc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXNBtH3cdX0FYT6EZlbhcXDrPTbtr9lwU',
    appId: '1:1013247766191:ios:fb5a01aa649cb5f79bae5a',
    messagingSenderId: '1013247766191',
    projectId: 'mysafespaceapp-d5bc3',
    databaseURL: 'https://mysafespaceapp-d5bc3-default-rtdb.firebaseio.com',
    storageBucket: 'mysafespaceapp-d5bc3.appspot.com',
    iosClientId: '1013247766191-pf1llkd9trr8v63vbd1ocb7lk814jbc1.apps.googleusercontent.com',
    iosBundleId: 'net.mysafespace.safeSpacePluginExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXNBtH3cdX0FYT6EZlbhcXDrPTbtr9lwU',
    appId: '1:1013247766191:ios:fb5a01aa649cb5f79bae5a',
    messagingSenderId: '1013247766191',
    projectId: 'mysafespaceapp-d5bc3',
    databaseURL: 'https://mysafespaceapp-d5bc3-default-rtdb.firebaseio.com',
    storageBucket: 'mysafespaceapp-d5bc3.appspot.com',
    iosClientId: '1013247766191-pf1llkd9trr8v63vbd1ocb7lk814jbc1.apps.googleusercontent.com',
    iosBundleId: 'net.mysafespace.safeSpacePluginExample',
  );
}
